create:
  handler: src/todos/create.create
  events:
    - http:
        path: todos
        method: post
        cors: false

list:
  handler: src/todos/list.list
  events:
    - http:
        path: todos
        method: get
        cors: false

get:
  handler: src/todos/get.get
  events:
    - http:
        path: todos/{id}
        method: get
        cors: false

update:
  handler: src/todos/update.update
  events:
    - http:
        path: todos/{id}
        method: put
        cors: false

delete:
  handler: src/todos/delete.delete
  events:
    - http:
        path: todos/{id}
        method: delete
        cors: false
